### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Tinker-Bel** [konnod/Email-checker#1]
HEllo,
I'm trying to get this working, but I'm getting an Imap connection error.
I know that the serveradress, port, login and password are correct (I use them in another application) and still I'm getting a connection error......

Here is the error:
Checking IMAP
[ MAIL IMAP ] Connecting to imap.server.com:993
[ MAIL IMAP ] ERROR: connecting failed

kind regards,

**Comment by TheProp3r** [comment]
There seems to be an error in the esp8266 arduino library. Downgrading to version 2.4.2 fixes it for me.

**Comment by Tinker-Bel** [comment]
yes, it works! I would not have found this in a million years!
Thanks!
